
modLoader="javafml"
loaderVersion="[37,)"
license="GNU General Public License 3"
issueTrackerURL="https://github.com/ate47/AdvancedCreativeTab/issues"
[[mods]]
	modId="act"
	version="2.4.0"
	displayName="Advanced creative tab 2"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/advanced-extended-creative-mode"
	logoFile="logo.png"
	authors="ATE47"
	description="Borried about the old minecraft stuff ? This mod is made for you ! it add new items modifiers for your creative mode"

[[dependencies.act]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"

